<?php
define('SESSION_USERID', 'userID');
define('SESSION_MAIL', 'userEmail');
define('REMEMBER_ME_COOKIE_EXPIRY', 2592000);
define('REMEMBER_ME_COOKIE_NAME', 'rememberMe');
define('SESSION_PRIVILEGE', 'Standard');
define('STANDARD', 'Standard');
define('MODERATOR', 'Moderator');
define('ADMIN', 'Admin');

define('MAX_PROJECTS_PROFILE', 60);
define('MAX_DEGREES_PROFILE', 10);
define('MAX_COURSES_PROFILE', 200);
define('MAX_UPLOAD_SIZE', 5000000);

define('DATABASE_SERVER_NAME', 'localhost');
define('DATABASE_USER_NAME', 'root');
define('DATABASE_PASSWORD', '');
define('DATABASE_NAME', '9.0');

define('INVALID_UPLOAD', 'INVALID_UPLOAD');
define('EMPTY_FIELDS', 'EMPTY_FIELDS');
define('INVALID_USERNAME', 'INVALID_USERNAME');
define('INVALID_MAIL', 'INVALID_EMAIL');
define('INVALID_PASSWORD_MATCH', 'INVALID_PASSWORD_MATCH');
define('EMAIL_TAKEN', 'EMAIL_TAKEN');
define('INVALID_CREDENTIALS', 'INVALID_CREDENTIALS');
define('EMPTY_PROJECT', 'EMPTY_PROJECT');
define('INVALID_PROJECT_LINK', 'INVALID_PROJECT_LINK');
define('INVALID_FIRST_NAME', 'INVALID_FIRST_NAME');
define('INVALID_LAST_NAME', 'INVALID_LAST_NAME');
define('INVALID_DATES', 'INVALID_DATES');
define('INVALID_ACTIVEDEGREEID', 'INVALID_ACTIVEDEGREEID');

define('IMAGE_UPLOAD_WIDTH', 300);
define('IMAGE_UPLOAD_HEIGHT', 300);
